"use client";
import Contact from "@/components/Contact";
import Layout from "@/components/Layout";
import Head from "next/head";
import React from "react";
import designPic from "../../public/images/profile/Untitled design.png";
import TransitionEffect from "@/components/TransitionEffect";

const contact = () => {
  return (
    <>
      <Head>
        <title>Contact Us</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main>
        <Layout>
          <div className="grid grid-cols-2 gap-4 mt-4 w-full col-span-2 xl:grid-cols-1 xl:justify-center">
            <Contact />
            <div className="xl:hidden">
              <img
                src={designPic.src}
                alt="RudrikRaina"
                className="w-full h-auto"
                loading="eager"
              />
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
};

export default contact;
